services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ideatec-api
    ports:
      - "5004:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__ProductionConnection=server=db-static-web-app-do-user-29042775-0.e.db.ondigitalocean.com;port=25060;database=ideafactu;uid=factuadmin;password=AVNS_yjLC46it_1VXv0zcI9C;Charset=utf8mb4;Pooling=true;MinimumPoolSize=3;MaximumPoolSize=50;ConnectionTimeout=5;Allow User Variables=True;SslMode=Required;
      - ConnectionStrings__BetaConnection=server=63.251.107.133;port=3306;database=ideafactu;uid=velsatuser;password=velsatAPI23;Charset=utf8mb4;Pooling=true;MinimumPoolSize=2;MaximumPoolSize=30;ConnectionTimeout=5;Allow User Variables=True;SslMode=None;
      - JwtSettings__Secret=0c6e838cbd906bab6c80bfeff56fb3e7c6f2c64ba7739054934953acce297c95
      - JwtSettings__Issuer=IdeatecAPI
      - JwtSettings__Audience=IdeatecClient
      - JwtSettings__AccessTokenExpirationMinutes=30
      - JwtSettings__RefreshTokenExpirationDays=7
      - Storage__RutaXml=/app/storage
      - Storage__MicroservicioUrl=https://do.velsat.pe:8443/storagefactunet
      - WebSocket__NotifyUrl=https://do.velsat.pe:8443/notify/notify
      - Smtp__ApiKey=mlsn.703ae2fd8dc61cdc70947b80c28ff29e2ffb9a4e50bd0b1cc73ca6ea6d09ecd7
      - Smtp__FromEmail=factufly@ideatec.com.pe
      - Smtp__FromName=Factufly
      - App__FrontendUrl=https://factufly.ideatec.com.pe
    volumes:
      - facturacion_storage:/app/storage
    restart: unless-stopped

volumes:
  facturacion_storage:
    driver: local
